### PR TITLE
filename depends on version

### PR DESCRIPTION
**Pull request by Blaze34**
Change download URL conditionally by package version

### CODE REVIEW

**Comment by idrisakmal** [comment]
any updates on this?

**Comment by Blaze34** [comment]
@idrisakmal I guess that nobody cares. You may install plugin from my repo and use it. I solved my problem in this way. Good luck

**Comment by bepisdev** [comment]
@Blaze34 myself and some others have also submitted PRs to patch this and related issues with this plugin. I just closed my last attempt at a PR to patch the incorrect URL for the Linux archive a month ago. I've also submitted a PR to the ASDF plugins repo to redirect the install to a fork I made of this. I have had nothing from either.

My evidence would only lead to me agreeing with you.

**Comment by sylph01** [comment]
Sorry for the very late response... I've been away from using MongoDB for a long time, and haven't been able to keep up.
Last time I checked I tried to merge @joshburnsxyz 's pull request, but it was already closed when I checked. If this fixes both issues, then I have no problem merging this.

**Comment by bepisdev** [comment]
@sylph01 Apologies if im coming across confrontational, not my intention. I was under the assumption the project was abandoned and closed the PR in favour of the one made to asdf-plugins I mentioned.

**Comment by chaosharmonic** [comment]
FYI I just installed this version a couple days ago and the new merge is still broken on Linux. (@joshburnsxyz's fix does solve this though.)

**Comment by Blaze34** [comment]
> FYI I just installed this version a couple days ago and the new merge is still broken on Linux. (@joshburnsxyz's fix does solve this though.)

It should be checked for your case separately.
Give additional information as much as possible: 
- OS
- arch
- version that you tried to install
- line from terminal which produced by `echo "download_url $download_url"`

**Comment by backail** [comment]
I am having the error as well:

* OS - Ubuntu 20.04.3 LTS (5.4.0-97-generic)
* Arch - x86_64
* version that you tried to install - _latest_
* line from terminal ... - _download_url_

Command: `asdf install mongodb latest`
Output:
```
download_url https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-5.2.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    579      0 --:--:-- --:--:-- --:--:--   578

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Blaze34** [comment]
Yes. It's true. You tried download archive from `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-5.2.0.tgz`
but it doesn't exist.
For Ubuntu 20.04 it should be 
`https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-5.2.0.tgz`

so missed part `-ubuntu2004` (same for all linux/unix based platforms. Ubuntu, Suse, Debial, etc)

I've fixed downloading for MacOS only and it's still correct.

P.S. The fastest solution - use docker.

**Pull request merged**
